[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "spec-validator"
version = "0.1.0"
description = "Your project description"
authors = [{name = "Ben Alexander", email = "spec-validator@ben-alexander.com"},]

dependencies = [
    "pydantic>=2.10.2",
    "pyyaml"
]
requires-python = ">=3.13"

[project.optional-dependencies]

dev = [
    "pytest>=7.0",
    "pytest-cov",
    "mutmut>=2.4.3",
    "hypothesis>=6.122.0",
]

build = [
    "requests"
]

[tool.setuptools]
packages = ["specs"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]