name: Checks

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: check_changes
        with:
          filters: |
            run_python_checks:
              - '**' # Match everything initially
              - '!.github/**'
              - '!tests/data/**'
              - '!bin/**'
              - '!.dockerignore'
              - '!LICENSE'
              - '!README.md'

      - if: steps.check_changes.outputs.run_python_checks == 'true'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Formatting
        run: uv run black .

      - name: Import sorting
        run: uv run isort .

      - name: Linting
        run: uv run pylint amati
      
      - name: Test Linting
        run: uv run pylint tests

      - name: Testing
        run: uv run pytest -m"not external" --cov

      - name: Doctests
        run: uv run pytest --doctest-modules amati/

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage-comment-action
          path: python-coverage-comment-action.txt